app:
  git-hub-base-url: https://api.github.com
  stack-over-flow-base-url: https://api.stackexchange.com
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

spring:
  application:
    name: scrapper
server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
