app:
  git-hub-base-url: https://api.github.com
  stack-over-flow-base-url: https://api.stackexchange.com
  interval-check-time: 1000000
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
