app:
  git-hub-base-url: https://api.github.com
  stack-over-flow-base-url: https://api.stackexchange.com
  interval-check-time: 1200000
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  database-access-type: jpa
  retry-policy:
    back-off-type: exp
    max-attempts: 3
    retry-codes: 502
    delay: 1000
  rate-limiting:
    enable: true
    tokens-capacity: 120
    tokens-per-second: 10
  kafka:
    topic: messages.updates
    bootstrap-servers: localhost:29091, localhost:29092, localhost:9093
    replication-factor: 2
    partitions: 2
    acks-mode: all
    delivery-timeout: 50000
    linger: 10000
    batch-size: 100000
    max-in-flight-per-connection: 5
    enable-idempotence: true
  use-queue: true

spring:
  main:
    web-application-type: reactive
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: info, health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true


