app:
  telegram-token: ${TOKEN}
  retry-policy:
    back-off-type: exp
    max-attempts: 3
    retry-codes: 502
    delay: 1000
  rate-limiting:
    enable: true
    tokens-capacity: 120
    tokens-per-second: 10
  kafka:
    group-id: messages-group
    bootstrap-servers: localhost:29091, localhost:29092, localhost:9093
    auto-offset-reset: latest
    max-poll-interval-ms: 300000
    enable-auto-commit: false
    concurrency: 2
    dlq:
      topic: messages.updates_dlq
      replication-factor: 2
      partitions: 2
      acks-mode: all
      delivery-timeout: 50000
      linger: 10000
      batch-size: 100000
      max-in-flight-per-connection: 5

spring:
  main:
    web-application-type: reactive
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: info, health, prometheus
      path-mapping:
        prometheus: metrics
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
